### ISSUE TITLE
Error after installing Limas

### ISSUE THREAD

**Issue by Datinhkhach** [Lopo/Limas#6]
I tried installing Limas and didn't get any error messages, but when I entered the Limas web interface, I got the error: "Critical ErrorThe server returned a response which we were not able to interpret."

Here is full error log :

Critical` Error

Details
==================================
The server returned a response which we were not able to interpret.

Request
==================================
GET http://pc.local/api/system_notices?_dc=1720681634186

Response Status Code
==================================
404

Response
==================================
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.52 (Ubuntu) Server at pc.local Port 80</address>
</body></html>

Server Configuration
==================================
doctrine_orm_version: 2.17.2.0
doctrine_dbal_version: 3.7.2.0
doctrine_common_version: 3.4.3.0
php_version: 8.2.21
auto_start_session: true
maxUploadSize: 2097152
isOctoPartAvailable: true
availableImageFormats: image/gif,image/jpeg,image/png,image/vnd.wap.wbmp,image/xbm,image/bmp,image/webp,image/avif
max_users: unlimited
authentication_provider: HTTPBasic
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true
defaultGridPresets: []
autoLoginUsername: admin
autoLoginPassword: admin

**Comment by Lopo** [comment]
that's a bit strange ...
it should return E401 (unauthorized) or code 200 with `Content-Type: application/ld+json; charset=utf-8` and content ```{"@context":"\/api\/contexts\/SystemNotice","@id":"\/api\/system_notices","@type":"hydra:Collection","hydra:totalItems":0,"hydra:member":[]}```

so my guess is problem with server (nginx/apache/...) config (root dir, index file)

**Comment by Datinhkhach** [comment]
Here is my apache config : 


<VirtualHost *:80>
    ServerName pc.local
    ServerAlias www.pc.local

    DocumentRoot /var/www/limas/public
    <Directory /var/www/limas/public>
        AllowOverride All
        Order Allow,Deny
        Allow from All
    </Directory>

    ErrorLog /var/log/apache2/limas_error.log
    CustomLog /var/log/apache2/limas_access.log combined
</VirtualHost>

**Comment by Lopo** [comment]
I don't use Apache, so unable to say if it's ok or what problem it has
but here's my nginx config if it helps you:

```
server {
	listen 80;
	server_name limas.lnet;
	return 301 https://limas.lnet$request_uri;
	}

server {
	listen 443 ssl;
	http2 on;
	server_name limas.lnet;

	root /srv/http/Limas/public;
	index index.php;
	ssl_certificate /etc/nginx/certs/limas.lnet.pem;
	ssl_certificate_key /etc/nginx/certs/limas.lnet-key.pem;

	access_log /var/log/nginx/limas.lnet-access.log;
	error_log /var/log/nginx/limas.lnet-error.log;

	add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";

	location / {
		try_files $uri /index.php$is_args$args;
		}
	location ~ \.php(/|$) {
		fastcgi_pass unix:/run/php82-fpm/php-fpm.sock;
		fastcgi_split_path_info ^(.+\.php)(/.*)$;
		include /etc/nginx/fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
		fastcgi_param DOCUMENT_ROOT $realpath_root;
		fastcgi_read_timeout 600;
		}
	}
```

next step check your apache logs if there is any clue/info
then symfony profiler: http://pc.local/_profiler

**Comment by Datinhkhach** [comment]
Here are my notes on how to install Limas step by step. Suitable for people with poor technology like me. If possible, please provide more detailed and accurate instructions, thank you very much.
[Install.txt](https://github.com/user-attachments/files/16174015/Install.txt)

**Comment by Trickfilm400** [comment]
In the Docker which is not documented yet I'm using the following: Maybe you need the `FallbackResource` directive?
```
        <Directory /var/www/limas/public>
            AllowOverride None
            Require all granted
            FallbackResource /index.php
        </Directory>
```

**Comment by Datinhkhach** [comment]
> In the Docker which is not documented yet I'm using the following: Maybe you need the `FallbackResource` directive?

> ```
> ```

After inserting the value "FallbackResource /index.php", the web interface is accessible and no longer reports errors. However, I have to access it by IP and cannot use the "pc.local" domain anymore. When accessing using the "pc.local" domain, there will be an error message: This site can't be reached pc.local refused to connect.

**Comment by Trickfilm400** [comment]
Hm, interesting. This should work

Can you double-verify, that `pc.local` resolves to the correct IP address? (`nslookup pc.local` or `host pc.local` for linux)

Is the error message (`This site can't be reached pc.local refused to connect.`) from the browser? or from a webserver?

**Comment by Datinhkhach** [comment]
The domain working fine . Ping and nslookup commands both respond ok .

 C:\Users\datinhkhach>nslookup pc.local
Server:  UnKnown
Address:  192.168.2.14

Name:    pc.local
Address:  **192.168.77.140**

PS : sorry for my bad english . Im using gg translator.

**Comment by Datinhkhach** [comment]
Thanks for yours help, I tried using another browser to access the domain "pc.local" and it worked normally. Seems to be a web browser session saving issue.
